spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: pw3306
  jpa:
    show-sql: true
server:
  port: 8082
girl:
  name: yly
  age: 20
env: dev8
