spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.21.239.18:3306/springcloud_shell?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
  redis:
    host: 10.21.239.4
    port: 6379
server:
  port: 8081
